name: Setup Node Environment
description: Sets up Node.js environment using .nvmrc

runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      working-directory: data
      run: |
        git config --global user.name "${{ env.GH_USER }}"
        git config --global user.email "${{ env.GH_USER }}@users.noreply.github.com"
        git remote set-url origin https://${{ env.GH_USER }}:${{ env.GH_TOKEN }}@github.com/bgrgicak/Playground-compatibility-reports.git
      env:
        GH_USER: ${{ env.GH_USER }}
        GH_TOKEN: ${{ env.GH_TOKEN }}

    - name: Git Submodule Update
      shell: bash
      run: git submodule update --remote --recursive --depth 1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Install Dependencies
      shell: bash
      run: ./scripts/install-dependencies.sh
