name: Setup Node Environment
description: Sets up Node.js environment using .nvmrc

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "bgrgicak"
        git config --global user.email "bgrgicak@users.noreply.github.com"

    - name: Set Node version
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Install dependencies
      shell: bash
      run: npm install
