name: Setup Node Environment
description: Sets up Node.js environment using .nvmrc

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{ env.GH_USER }}"
        git config --global user.email "${{ env.GH_USER }}@users.noreply.github.com"

    - name: Git Submodule Update
      shell: bash
      run: |
        git pull --recurse-submodules origin ${{ github.event.pull_request.head.ref }}
        git submodule update --remote --recursive

    - name: Set Node version
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

    - name: Install Dependencies
      shell: bash
      run: ./scripts/install-dependencies.sh
