name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 UTC every day
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Add this line to grant write permissions

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tester.sh
        run: ./tester.sh

      - name: Run parser.sh
        run: ./parser.sh

      - name: Run reporter.sh
        run: ./reporter.sh

      - name: GIT commit and push all changed files
        run: |
          git config --global user.name "bgrgicak"
          git config --global user.email "bgrgicak@users.noreply.github.com"
          git add .
          git commit -a -m "Daily update: $(date +'%Y-%m-%d')"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push
