name: Run Tests on Pull Request

permissions:
  contents: write

on:
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - name: Test git push
        run: |
          git config --global user.email "${{ env.GH_USER }}@users.noreply.github.com"
          git config --global user.name "${{ env.GH_USER }}"
          cd data
          git fetch origin main
          git checkout main
          git pull origin main
          echo "update" >> README.md
          git add README.md
          git commit -m "update readme"
          git remote set-url origin https://${{ env.GH_USER }}:${{ env.GH_TOKEN }}@github.com/bgrgicak/Playground-compatibility-reports.git
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}
          GH_USER: botbero



      # - uses: ./.github/actions/setup-test-environment/
      #   env:
      #     token: ${{ secrets.BOTBERO_TOKEN }}

      # - name: Run tests
      #   run: |
      #     ./scripts/unit-tests/test.sh
      #   env:
      #     GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}
      #     GH_USER: botbero
