name: Run Tests on Pull Request

permissions:
  contents: write

on:
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          token: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run tests
        run: |
          # Configure git to use the token for authentication
          git config --global user.email "botbero@users.noreply.github.com"
          git config --global user.name "botbero"
          git config --global url."https://${{ secrets.BOTBERO_TOKEN }}@github.com/".insteadOf "https://github.com/"

          # Run the test script and store its exit code
          ./scripts/unit-tests/test.sh
