name: Test themes

on:
  schedule:
    # Run every 30 minutes
    - cron: '10 * * * *'
    - cron: '40 * * * *'

  workflow_dispatch:
    inputs:
      batch_size:
        type: number
        default: 10

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        range:
          - "_0123456789abcdefghijk" # ~6.6k themes
          - "lmnopqrstuvwxyz"        # ~6.7k themes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          GH_USER: ${{ secrets.BOTBERO_USER }}
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run theme batch
        shell: bash
        run: |
          BATCH_SIZE=${{ inputs.batch_size }}
          if [ -z "$BATCH_SIZE" ]; then
            BATCH_SIZE=70
          fi
          npm run test:batch -- --themes --limit $BATCH_SIZE --prefix-chars ${{ matrix.range }}
