name: Test themes

on:
  # schedule:
    # Run every 10 minutes with a 2 minute delay compared to plugin runs
    # - cron: '2,12,22,32,42,52 * * * *'
  workflow_dispatch:
    inputs:
      batch_size:
        type: number
        default: 10

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          GH_USER: ${{ secrets.BOTBERO_USER }}
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run theme batch
        run: ./scripts/run-batch.sh --batch-size ${{ inputs.batch_size }} --themes

