name: Test themes

on:
  # schedule:
    # - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual triggering
    inputs:
      batch_size:
        type: number
        default: 100

permissions:
  contents: write  # Add this line to grant write permissions

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-test-environment/

      - name: Run theme batch
        run: ./scripts/run-batch.sh --batch-size ${{ inputs.batch_size }} --themes

