name: Test themes

on:
  schedule:
    # Run every 20 minutes with a 10 minute delay
    # to ensure it runs after plugin runs
    - cron: '10 * * * *'
    - cron: '30 * * * *'
    - cron: '50 * * * *'

  workflow_dispatch:
    inputs:
      batch_size:
        type: number
        default: 10

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          GH_USER: ${{ secrets.BOTBERO_USER }}
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run theme batch
        run: |
          BATCH_SIZE=${{ inputs.batch_size }}
          if [ -z "$BATCH_SIZE" ]; then
            BATCH_SIZE=50
          fi
          ./scripts/run-batch.sh --batch-size $BATCH_SIZE --themes
