name: Update available themes and plugins

on:
  # schedule:
    # - cron: '0 0 * * *'  # Run every day at midnight UTC
  workflow_dispatch:

jobs:

  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      with:
        submodules: recursive

      - name: Run update-available-themes-and-plugins.sh
        run: ./scripts/update-available-themes-and-plugins.sh
