name: Update available themes and plugins

on:
  # schedule:
    # - cron: '0 0 * * *'  # Run every day at midnight UTC
  workflow_dispatch:

jobs:

  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          GH_USER: ${{ secrets.BOTBERO_USER }}
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run update-available-themes-and-plugins.sh
        run: ./scripts/update-available-themes-and-plugins.sh

      - name: Save data
        run: |
          source ./scripts/save-data.sh
          save_data \
            --add logs/ \
            --message "Updated the list of plugins and themes on $(date +"%Y-%m-%d")" \
            --push

