name: Update error stats data

on:
  schedule:
    # Run every hour at minute 15
    # to ensure it runs before generate-reports
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:

  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOTBERO_TOKEN }}

      - uses: ./.github/actions/setup-test-environment/
        env:
          GH_USER: ${{ secrets.BOTBERO_USER }}
          GH_TOKEN: ${{ secrets.BOTBERO_TOKEN }}

      - name: Run update-error-stats-data.sh
        run: ./scripts/update-error-stats-data.sh

      - name: Save data
        run: |
          source ./scripts/save-data.sh
          save_data \
            --add logs/ \
            --message "Updated error stats on $(date +"%Y-%m-%d")" \
            --push
